kind: pipeline
name: default

workspace:
  path: /cfda-app

volumes:
  - name: webroot
    host:
      path: /root/www
  - name: pnpm-cache
    host:
      path: /root/.pnpm-cache
  - name: envfile
    host:
      path: /root/project-config/cfda-app/.env.production.local

trigger:
  branch:
    - master

steps:
  - name: build
    image: chiskat/baseline-node20:2026.1.14
    commands:
      - pnpm i
      - pnpm build
    volumes:
      - name: pnpm-cache
        path: /cfda-app/.pnpm-store
      - name: envfile
        path: /cfda-app/.env.production.local

  - name: deploy-upload-cdn
    image: plugins/s3
    settings:
      endpoint:
        from_secret: S3_ENDPOINT
      region:
        from_secret: S3_REGION
      bucket:
        from_secret: S3_BUCKET_NAME
      access_key:
        from_secret: S3_ACCESS_KEY_ID
      secret_key:
        from_secret: S3_SECRET_ACCESS_KEY
      source: ./public/**/*
      target: /paperplane-cfda
      strip_prefix: public

  - name: deploy
    image: alpine:3.20
    volumes:
      - name: webroot
        path: /webroot
    commands:
      - mkdir -p /webroot/paperplane-cfda/
      - rm -rf /webroot/paperplane-cfda/*
      - cp -rf ./dist/* /webroot/paperplane-cfda/
